name: couleur
description: "Ephemeral chat"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  ndk: ^0.5.0
  nip19: ^0.2.0
  nostr_widgets: ^0.0.3
  system_theme: ^3.1.2
  url_launcher: ^6.3.2
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
